services:
    nginx:
        image: nginx:latest
    port-forward:
        image: heyman/filtered-port-forward
        environment:
            - LOCAL_PORT=8091
            - REMOTE_PORT=80
            - REMOTE_HOST=nginx
            - ALLOWED_HOSTS=127.0.0.1,172.24.0.,192.168.0.1
        ports:
            - 8091:8091
